export const POPULAR_MEDIA = [
  {
    adult: false,
    backdrop_path: '/soQgquPkLmUu9eKLJJzuA4KZDyi.jpg',
    genre_ids: [80, 18, 9648],
    id: 69050,
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Riverdale',
    overview:
      'Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.',
    popularity: 2804.035,
    poster_path: '/c1ROxK1Afo6YuGi3j6ClXmrNcHi.jpg',
    first_air_date: '2017-01-26',
    name: 'Riverdale',
    vote_average: 8.471,
    vote_count: 13238,
  },
];

export const MEDIA_LIST = [
  {
    adult: false,
    backdrop_path: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    id: 66732,
    name: 'Stranger Things',
    original_language: 'en',
    original_name: 'Stranger Things',
    overview:
      'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    poster_path: '/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    media_type: 'tv',
    genre_ids: [18, 10765, 9648],
    popularity: 534.876,
    first_air_date: '2016-07-15',
    vote_average: 8.619,
    vote_count: 16518,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/rIe3PnM6S7IBUmvNwDkBMX0i9EZ.jpg',
    id: 1399,
    name: 'Game of Thrones',
    original_language: 'en',
    original_name: 'Game of Thrones',
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    media_type: 'tv',
    genre_ids: [10765, 18, 10759],
    popularity: 779.706,
    first_air_date: '2011-04-17',
    vote_average: 8.44,
    vote_count: 22388,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/2kRqclTa8OCF9ZxMQZcBhfdzsRs.jpg',
    id: 1402,
    name: 'The Walking Dead',
    original_language: 'en',
    original_name: 'The Walking Dead',
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    poster_path: '/n7PVu0hSz2sAsVekpOIoCnkWlbn.jpg',
    media_type: 'tv',
    genre_ids: [10759, 18, 10765],
    popularity: 915.772,
    first_air_date: '2010-10-31',
    vote_average: 8.12,
    vote_count: 15674,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/wZMY9X8jtSS5GXFue2lvhgaJkii.jpg',
    id: 42009,
    name: 'Black Mirror',
    original_language: 'en',
    original_name: 'Black Mirror',
    overview:
      "Over the last ten years, technology has transformed almost every aspect of our lives before we've had time to stop and question it. In every home; on every desk; in every palm - a plasma screen; a monitor; a smartphone - a black mirror of our 21st Century existence.",
    poster_path: '/5UaYsGZOFhjFDwQh6GuLjjA1WlF.jpg',
    media_type: 'tv',
    genre_ids: [10765, 18, 9648],
    popularity: 252.86,
    first_air_date: '2011-12-04',
    vote_average: 8.303,
    vote_count: 4552,
    origin_country: ['GB'],
  },
  {
    adult: false,
    backdrop_path: '/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg',
    id: 1396,
    name: 'Breaking Bad',
    original_language: 'en',
    original_name: 'Breaking Bad',
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: '/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg',
    media_type: 'tv',
    genre_ids: [18, 80],
    popularity: 767.492,
    first_air_date: '2008-01-20',
    vote_average: 8.897,
    vote_count: 12864,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/uJUe985oIuRiD3hmHQYskIMc2WU.jpg',
    id: 62560,
    name: 'Mr. Robot',
    original_language: 'en',
    original_name: 'Mr. Robot',
    overview:
      'A contemporary and culturally resonant drama about a young programmer, Elliot, who suffers from a debilitating anti-social disorder and decides that he can only connect to people by hacking them. He wields his skills as a weapon to protect the people that he cares about. Elliot will find himself in the intersection between a cybersecurity firm he works for and the underworld organizations that are recruiting him to bring down corporate America.',
    poster_path: '/oKIBhzZzDX07SoE2bOLhq2EE8rf.jpg',
    media_type: 'tv',
    genre_ids: [80, 18],
    popularity: 132.836,
    first_air_date: '2015-06-24',
    vote_average: 8.246,
    vote_count: 4241,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/rBF8wVQN8hTWHspVZBlI3h7HZJ.jpg',
    id: 60625,
    name: 'Rick and Morty',
    original_language: 'en',
    original_name: 'Rick and Morty',
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path: '/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg',
    media_type: 'tv',
    genre_ids: [16, 35, 10765, 10759],
    popularity: 1631.805,
    first_air_date: '2013-12-02',
    vote_average: 8.701,
    vote_count: 8981,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/uL6Ad12W09L1sfuOE2pcTeak7bt.jpg',
    id: 87108,
    name: 'Chernobyl',
    original_language: 'en',
    original_name: 'Chernobyl',
    overview:
      'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
    poster_path: '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
    media_type: 'tv',
    genre_ids: [18],
    popularity: 267.153,
    first_air_date: '2019-05-06',
    vote_average: 8.659,
    vote_count: 5606,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/nDOIsgCYZqEMvomSR6t9QUIPZJS.jpg',
    id: 60622,
    name: 'Fargo',
    original_language: 'en',
    original_name: 'Fargo',
    overview:
      'A close-knit anthology series dealing with stories involving malice, violence and murder based in and around Minnesota.',
    poster_path: '/6U9CPeD8obHzweikFhiLhpc7YBT.jpg',
    media_type: 'tv',
    genre_ids: [80, 18],
    popularity: 1825.686,
    first_air_date: '2014-04-15',
    vote_average: 8.3,
    vote_count: 2380,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/ex4kvQb0Ski5KL2fsnKQU2hV3oo.jpg',
    id: 1425,
    name: 'House of Cards',
    original_language: 'en',
    original_name: 'House of Cards',
    overview:
      'Set in present day Washington, D.C., House of Cards is the story of Frank Underwood, a ruthless and cunning politician, and his wife Claire who will stop at nothing to conquer everything. This wicked political drama penetrates the shadowy world of greed, sex and corruption in modern D.C.',
    poster_path: '/hKWxWjFwnMvkWQawbhvC0Y7ygQ8.jpg',
    media_type: 'tv',
    genre_ids: [18],
    popularity: 235.138,
    first_air_date: '2013-02-01',
    vote_average: 8.041,
    vote_count: 2479,
    origin_country: ['US'],
  },
];
